// Code generated by pigeon; DO NOT EDIT.

package model_data_type

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func parserBoolPtr(b bool) *bool {
	return &b
}

var g = &grammar{
	rules: []*rule{
		{
			name: "RootDataType",
			pos:  position{line: 15, col: 1, offset: 107},
			expr: &actionExpr{
				pos: position{line: 15, col: 17, offset: 123},
				run: (*parser).callonRootDataType1,
				expr: &seqExpr{
					pos: position{line: 15, col: 17, offset: 123},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 15, col: 17, offset: 123},
							label: "dataType",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 26, offset: 132},
								name: "DataType",
							},
						},
						&notExpr{
							pos: position{line: 15, col: 35, offset: 141},
							expr: &anyMatcher{
								line: 15, col: 36, offset: 142,
							},
						},
					},
				},
			},
		},
		{
			name: "DataType",
			pos:  position{line: 19, col: 1, offset: 183},
			expr: &choiceExpr{
				pos: position{line: 19, col: 13, offset: 195},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 19, col: 13, offset: 195},
						name: "RecordDataType",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 30, offset: 212},
						name: "CollectionDataType",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 51, offset: 233},
						name: "AtomicDataType",
					},
				},
			},
		},
		{
			name: "RecordDataType",
			pos:  position{line: 21, col: 1, offset: 249},
			expr: &actionExpr{
				pos: position{line: 21, col: 19, offset: 267},
				run: (*parser).callonRecordDataType1,
				expr: &seqExpr{
					pos: position{line: 21, col: 19, offset: 267},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 21, col: 19, offset: 267},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 21, col: 23, offset: 271},
							expr: &ruleRefExpr{
								pos:  position{line: 21, col: 23, offset: 271},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 21, col: 27, offset: 275},
							label: "fields",
							expr: &ruleRefExpr{
								pos:  position{line: 21, col: 34, offset: 282},
								name: "FieldList",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 21, col: 44, offset: 292},
							expr: &ruleRefExpr{
								pos:  position{line: 21, col: 44, offset: 292},
								name: "ws",
							},
						},
						&litMatcher{
							pos:        position{line: 21, col: 48, offset: 296},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "FieldList",
			pos:  position{line: 33, col: 1, offset: 537},
			expr: &actionExpr{
				pos: position{line: 33, col: 14, offset: 550},
				run: (*parser).callonFieldList1,
				expr: &seqExpr{
					pos: position{line: 33, col: 14, offset: 550},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 33, col: 14, offset: 550},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 20, offset: 556},
								name: "Field",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 26, offset: 562},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 33, col: 31, offset: 567},
								expr: &seqExpr{
									pos: position{line: 33, col: 33, offset: 569},
									exprs: []any{
										&zeroOrOneExpr{
											pos: position{line: 33, col: 33, offset: 569},
											expr: &ruleRefExpr{
												pos:  position{line: 33, col: 33, offset: 569},
												name: "ws",
											},
										},
										&litMatcher{
											pos:        position{line: 33, col: 37, offset: 573},
											val:        ";",
											ignoreCase: false,
											want:       "\";\"",
										},
										&zeroOrOneExpr{
											pos: position{line: 33, col: 41, offset: 577},
											expr: &ruleRefExpr{
												pos:  position{line: 33, col: 41, offset: 577},
												name: "ws",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 45, offset: 581},
											name: "Field",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 33, col: 54, offset: 590},
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 54, offset: 590},
								name: "ws",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 33, col: 58, offset: 594},
							expr: &litMatcher{
								pos:        position{line: 33, col: 58, offset: 594},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 43, col: 1, offset: 853},
			expr: &actionExpr{
				pos: position{line: 43, col: 10, offset: 862},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 43, col: 10, offset: 862},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 43, col: 10, offset: 862},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 15, offset: 867},
								name: "FieldName",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 43, col: 25, offset: 877},
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 25, offset: 877},
								name: "ws",
							},
						},
						&litMatcher{
							pos:        position{line: 43, col: 29, offset: 881},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 43, col: 33, offset: 885},
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 33, offset: 885},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 43, col: 37, offset: 889},
							label: "dataType",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 46, offset: 898},
								name: "DataType",
							},
						},
					},
				},
			},
		},
		{
			name: "FieldName",
			pos:  position{line: 50, col: 1, offset: 1006},
			expr: &actionExpr{
				pos: position{line: 50, col: 14, offset: 1019},
				run: (*parser).callonFieldName1,
				expr: &seqExpr{
					pos: position{line: 50, col: 14, offset: 1019},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 50, col: 14, offset: 1019},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 50, col: 23, offset: 1028},
							expr: &charClassMatcher{
								pos:        position{line: 50, col: 23, offset: 1028},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "CollectionDataType",
			pos:  position{line: 54, col: 1, offset: 1075},
			expr: &actionExpr{
				pos: position{line: 54, col: 23, offset: 1097},
				run: (*parser).callonCollectionDataType1,
				expr: &seqExpr{
					pos: position{line: 54, col: 23, offset: 1097},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 54, col: 23, offset: 1097},
							label: "uniqueFlag",
							expr: &zeroOrOneExpr{
								pos: position{line: 54, col: 34, offset: 1108},
								expr: &seqExpr{
									pos: position{line: 54, col: 36, offset: 1110},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 54, col: 36, offset: 1110},
											val:        "unique",
											ignoreCase: false,
											want:       "\"unique\"",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 45, offset: 1119},
											name: "ws",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 51, offset: 1125},
							label: "multiplicity",
							expr: &zeroOrOneExpr{
								pos: position{line: 54, col: 64, offset: 1138},
								expr: &ruleRefExpr{
									pos:  position{line: 54, col: 64, offset: 1138},
									name: "Multiplicity",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 54, col: 78, offset: 1152},
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 78, offset: 1152},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 82, offset: 1156},
							label: "collectionType",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 97, offset: 1171},
								name: "CollectionTypeKeyword",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 119, offset: 1193},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 54, col: 122, offset: 1196},
							val:        "of",
							ignoreCase: false,
							want:       "\"of\"",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 127, offset: 1201},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 54, col: 130, offset: 1204},
							label: "atomic",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 137, offset: 1211},
								name: "AtomicDataType",
							},
						},
					},
				},
			},
		},
		{
			name: "CollectionTypeKeyword",
			pos:  position{line: 105, col: 1, offset: 2234},
			expr: &actionExpr{
				pos: position{line: 105, col: 26, offset: 2259},
				run: (*parser).callonCollectionTypeKeyword1,
				expr: &choiceExpr{
					pos: position{line: 105, col: 28, offset: 2261},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 105, col: 28, offset: 2261},
							val:        "stack",
							ignoreCase: false,
							want:       "\"stack\"",
						},
						&litMatcher{
							pos:        position{line: 105, col: 38, offset: 2271},
							val:        "unordered",
							ignoreCase: false,
							want:       "\"unordered\"",
						},
						&litMatcher{
							pos:        position{line: 105, col: 52, offset: 2285},
							val:        "ordered",
							ignoreCase: false,
							want:       "\"ordered\"",
						},
						&litMatcher{
							pos:        position{line: 105, col: 64, offset: 2297},
							val:        "queue",
							ignoreCase: false,
							want:       "\"queue\"",
						},
					},
				},
			},
		},
		{
			name: "Multiplicity",
			pos:  position{line: 109, col: 1, offset: 2340},
			expr: &actionExpr{
				pos: position{line: 109, col: 17, offset: 2356},
				run: (*parser).callonMultiplicity1,
				expr: &seqExpr{
					pos: position{line: 109, col: 17, offset: 2356},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 109, col: 17, offset: 2356},
							label: "min",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 21, offset: 2360},
								name: "Integer",
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 29, offset: 2368},
							label: "suffix",
							expr: &zeroOrOneExpr{
								pos: position{line: 109, col: 36, offset: 2375},
								expr: &choiceExpr{
									pos: position{line: 109, col: 38, offset: 2377},
									alternatives: []any{
										&seqExpr{
											pos: position{line: 109, col: 38, offset: 2377},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 109, col: 38, offset: 2377},
													val:        "-",
													ignoreCase: false,
													want:       "\"-\"",
												},
												&labeledExpr{
													pos:   position{line: 109, col: 42, offset: 2381},
													label: "maxVal",
													expr: &ruleRefExpr{
														pos:  position{line: 109, col: 49, offset: 2388},
														name: "Integer",
													},
												},
											},
										},
										&litMatcher{
											pos:        position{line: 109, col: 59, offset: 2398},
											val:        "+",
											ignoreCase: false,
											want:       "\"+\"",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AtomicDataType",
			pos:  position{line: 125, col: 1, offset: 2813},
			expr: &actionExpr{
				pos: position{line: 125, col: 19, offset: 2831},
				run: (*parser).callonAtomicDataType1,
				expr: &labeledExpr{
					pos:   position{line: 125, col: 19, offset: 2831},
					label: "atomic",
					expr: &choiceExpr{
						pos: position{line: 125, col: 28, offset: 2840},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 125, col: 28, offset: 2840},
								name: "SpanType",
							},
							&ruleRefExpr{
								pos:  position{line: 125, col: 39, offset: 2851},
								name: "OrdEnumType",
							},
							&ruleRefExpr{
								pos:  position{line: 125, col: 53, offset: 2865},
								name: "EnumType",
							},
							&ruleRefExpr{
								pos:  position{line: 125, col: 64, offset: 2876},
								name: "ObjectType",
							},
							&ruleRefExpr{
								pos:  position{line: 125, col: 77, offset: 2889},
								name: "ReferenceType",
							},
							&ruleRefExpr{
								pos:  position{line: 125, col: 93, offset: 2905},
								name: "UnconstrainedType",
							},
						},
					},
				},
			},
		},
		{
			name: "SpanType",
			pos:  position{line: 129, col: 1, offset: 2949},
			expr: &actionExpr{
				pos: position{line: 129, col: 13, offset: 2961},
				run: (*parser).callonSpanType1,
				expr: &seqExpr{
					pos: position{line: 129, col: 13, offset: 2961},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 129, col: 13, offset: 2961},
							label: "lowerBracket",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 26, offset: 2974},
								name: "LowerBracket",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 39, offset: 2987},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 39, offset: 2987},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 43, offset: 2991},
							label: "lowerValue",
							expr: &choiceExpr{
								pos: position{line: 129, col: 56, offset: 3004},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 129, col: 56, offset: 3004},
										name: "Unconstrained",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 72, offset: 3020},
										name: "FractionValue",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 88, offset: 3036},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 88, offset: 3036},
								name: "ws",
							},
						},
						&litMatcher{
							pos:        position{line: 129, col: 92, offset: 3040},
							val:        "..",
							ignoreCase: false,
							want:       "\"..\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 97, offset: 3045},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 97, offset: 3045},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 101, offset: 3049},
							label: "higherValue",
							expr: &choiceExpr{
								pos: position{line: 129, col: 115, offset: 3063},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 129, col: 115, offset: 3063},
										name: "Unconstrained",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 131, offset: 3079},
										name: "FractionValue",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 147, offset: 3095},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 147, offset: 3095},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 151, offset: 3099},
							label: "higherBracket",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 165, offset: 3113},
								name: "HigherBracket",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 179, offset: 3127},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 179, offset: 3127},
								name: "ws",
							},
						},
						&litMatcher{
							pos:        position{line: 129, col: 183, offset: 3131},
							val:        "at",
							ignoreCase: false,
							want:       "\"at\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 188, offset: 3136},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 188, offset: 3136},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 192, offset: 3140},
							label: "precision",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 202, offset: 3150},
								name: "Float",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 208, offset: 3156},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 208, offset: 3156},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 212, offset: 3160},
							label: "units",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 218, offset: 3166},
								name: "Units",
							},
						},
					},
				},
			},
		},
		{
			name: "FractionValue",
			pos:  position{line: 186, col: 1, offset: 4413},
			expr: &actionExpr{
				pos: position{line: 186, col: 18, offset: 4430},
				run: (*parser).callonFractionValue1,
				expr: &seqExpr{
					pos: position{line: 186, col: 20, offset: 4432},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 186, col: 20, offset: 4432},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 186, col: 26, offset: 4438},
								name: "Integer",
							},
						},
						&labeledExpr{
							pos:   position{line: 186, col: 34, offset: 4446},
							label: "denom",
							expr: &zeroOrOneExpr{
								pos: position{line: 186, col: 40, offset: 4452},
								expr: &seqExpr{
									pos: position{line: 186, col: 42, offset: 4454},
									exprs: []any{
										&zeroOrOneExpr{
											pos: position{line: 186, col: 42, offset: 4454},
											expr: &ruleRefExpr{
												pos:  position{line: 186, col: 42, offset: 4454},
												name: "ws",
											},
										},
										&litMatcher{
											pos:        position{line: 186, col: 46, offset: 4458},
											val:        "/",
											ignoreCase: false,
											want:       "\"/\"",
										},
										&zeroOrOneExpr{
											pos: position{line: 186, col: 50, offset: 4462},
											expr: &ruleRefExpr{
												pos:  position{line: 186, col: 50, offset: 4462},
												name: "ws",
											},
										},
										&labeledExpr{
											pos:   position{line: 186, col: 54, offset: 4466},
											label: "denomValue",
											expr: &ruleRefExpr{
												pos:  position{line: 186, col: 65, offset: 4477},
												name: "Integer",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 198, col: 1, offset: 4749},
			expr: &actionExpr{
				pos: position{line: 198, col: 12, offset: 4760},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 198, col: 12, offset: 4760},
					expr: &charClassMatcher{
						pos:        position{line: 198, col: 12, offset: 4760},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 202, col: 1, offset: 4809},
			expr: &actionExpr{
				pos: position{line: 202, col: 10, offset: 4818},
				run: (*parser).callonFloat1,
				expr: &choiceExpr{
					pos: position{line: 202, col: 12, offset: 4820},
					alternatives: []any{
						&seqExpr{
							pos: position{line: 202, col: 12, offset: 4820},
							exprs: []any{
								&oneOrMoreExpr{
									pos: position{line: 202, col: 12, offset: 4820},
									expr: &charClassMatcher{
										pos:        position{line: 202, col: 12, offset: 4820},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 202, col: 19, offset: 4827},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 202, col: 23, offset: 4831},
									expr: &charClassMatcher{
										pos:        position{line: 202, col: 23, offset: 4831},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
						&seqExpr{
							pos: position{line: 202, col: 32, offset: 4840},
							exprs: []any{
								&zeroOrMoreExpr{
									pos: position{line: 202, col: 32, offset: 4840},
									expr: &charClassMatcher{
										pos:        position{line: 202, col: 32, offset: 4840},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 202, col: 39, offset: 4847},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 202, col: 43, offset: 4851},
									expr: &charClassMatcher{
										pos:        position{line: 202, col: 43, offset: 4851},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 202, col: 52, offset: 4860},
							expr: &charClassMatcher{
								pos:        position{line: 202, col: 52, offset: 4860},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "LowerBracket",
			pos:  position{line: 208, col: 1, offset: 4953},
			expr: &actionExpr{
				pos: position{line: 208, col: 17, offset: 4969},
				run: (*parser).callonLowerBracket1,
				expr: &choiceExpr{
					pos: position{line: 208, col: 19, offset: 4971},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 208, col: 19, offset: 4971},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&litMatcher{
							pos:        position{line: 208, col: 25, offset: 4977},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
					},
				},
			},
		},
		{
			name: "HigherBracket",
			pos:  position{line: 212, col: 1, offset: 5016},
			expr: &actionExpr{
				pos: position{line: 212, col: 18, offset: 5033},
				run: (*parser).callonHigherBracket1,
				expr: &choiceExpr{
					pos: position{line: 212, col: 20, offset: 5035},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 212, col: 20, offset: 5035},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&litMatcher{
							pos:        position{line: 212, col: 26, offset: 5041},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Unconstrained",
			pos:  position{line: 216, col: 1, offset: 5080},
			expr: &actionExpr{
				pos: position{line: 216, col: 18, offset: 5097},
				run: (*parser).callonUnconstrained1,
				expr: &litMatcher{
					pos:        position{line: 216, col: 18, offset: 5097},
					val:        "unconstrained",
					ignoreCase: false,
					want:       "\"unconstrained\"",
				},
			},
		},
		{
			name: "Units",
			pos:  position{line: 220, col: 1, offset: 5146},
			expr: &actionExpr{
				pos: position{line: 220, col: 10, offset: 5155},
				run: (*parser).callonUnits1,
				expr: &oneOrMoreExpr{
					pos: position{line: 220, col: 10, offset: 5155},
					expr: &charClassMatcher{
						pos:        position{line: 220, col: 10, offset: 5155},
						val:        "[a-zA-Z-]",
						chars:      []rune{'-'},
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "OrdEnumType",
			pos:  position{line: 224, col: 1, offset: 5199},
			expr: &actionExpr{
				pos: position{line: 224, col: 16, offset: 5214},
				run: (*parser).callonOrdEnumType1,
				expr: &seqExpr{
					pos: position{line: 224, col: 16, offset: 5214},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 224, col: 17, offset: 5215},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 224, col: 17, offset: 5215},
									val:        "ordered",
									ignoreCase: false,
									want:       "\"ordered\"",
								},
								&litMatcher{
									pos:        position{line: 224, col: 29, offset: 5227},
									val:        "ord",
									ignoreCase: false,
									want:       "\"ord\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 224, col: 36, offset: 5234},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 224, col: 39, offset: 5237},
							label: "enumeration",
							expr: &ruleRefExpr{
								pos:  position{line: 224, col: 51, offset: 5249},
								name: "EnumType",
							},
						},
					},
				},
			},
		},
		{
			name: "EnumType",
			pos:  position{line: 231, col: 1, offset: 5394},
			expr: &actionExpr{
				pos: position{line: 231, col: 13, offset: 5406},
				run: (*parser).callonEnumType1,
				expr: &seqExpr{
					pos: position{line: 231, col: 13, offset: 5406},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 231, col: 14, offset: 5407},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 231, col: 14, offset: 5407},
									val:        "enumeration",
									ignoreCase: false,
									want:       "\"enumeration\"",
								},
								&litMatcher{
									pos:        position{line: 231, col: 30, offset: 5423},
									val:        "enum",
									ignoreCase: false,
									want:       "\"enum\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 231, col: 38, offset: 5431},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 231, col: 42, offset: 5435},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 231, col: 42, offset: 5435},
									val:        "of",
									ignoreCase: false,
									want:       "\"of\"",
								},
								&litMatcher{
									pos:        position{line: 231, col: 49, offset: 5442},
									val:        "from",
									ignoreCase: false,
									want:       "\"from\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 231, col: 57, offset: 5450},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 231, col: 60, offset: 5453},
							label: "enumValues",
							expr: &zeroOrMoreExpr{
								pos: position{line: 231, col: 71, offset: 5464},
								expr: &anyMatcher{
									line: 231, col: 71, offset: 5464,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ObjectType",
			pos:  position{line: 257, col: 1, offset: 6101},
			expr: &actionExpr{
				pos: position{line: 257, col: 15, offset: 6115},
				run: (*parser).callonObjectType1,
				expr: &seqExpr{
					pos: position{line: 257, col: 15, offset: 6115},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 257, col: 16, offset: 6116},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 257, col: 16, offset: 6116},
									val:        "object",
									ignoreCase: false,
									want:       "\"object\"",
								},
								&litMatcher{
									pos:        position{line: 257, col: 27, offset: 6127},
									val:        "obj",
									ignoreCase: false,
									want:       "\"obj\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 257, col: 34, offset: 6134},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 257, col: 38, offset: 6138},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 257, col: 38, offset: 6138},
									val:        "of",
									ignoreCase: false,
									want:       "\"of\"",
								},
								&litMatcher{
									pos:        position{line: 257, col: 45, offset: 6145},
									val:        "from",
									ignoreCase: false,
									want:       "\"from\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 257, col: 53, offset: 6153},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 257, col: 56, offset: 6156},
							label: "content",
							expr: &zeroOrOneExpr{
								pos: position{line: 257, col: 64, offset: 6164},
								expr: &ruleRefExpr{
									pos:  position{line: 257, col: 64, offset: 6164},
									name: "Content",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceType",
			pos:  position{line: 268, col: 1, offset: 6399},
			expr: &actionExpr{
				pos: position{line: 268, col: 18, offset: 6416},
				run: (*parser).callonReferenceType1,
				expr: &seqExpr{
					pos: position{line: 268, col: 18, offset: 6416},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 268, col: 19, offset: 6417},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 268, col: 19, offset: 6417},
									val:        "reference",
									ignoreCase: false,
									want:       "\"reference\"",
								},
								&litMatcher{
									pos:        position{line: 268, col: 33, offset: 6431},
									val:        "ref",
									ignoreCase: false,
									want:       "\"ref\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 268, col: 40, offset: 6438},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 268, col: 44, offset: 6442},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 268, col: 44, offset: 6442},
									val:        "of",
									ignoreCase: false,
									want:       "\"of\"",
								},
								&litMatcher{
									pos:        position{line: 268, col: 51, offset: 6449},
									val:        "from",
									ignoreCase: false,
									want:       "\"from\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 268, col: 59, offset: 6457},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 268, col: 62, offset: 6460},
							label: "content",
							expr: &zeroOrOneExpr{
								pos: position{line: 268, col: 70, offset: 6468},
								expr: &ruleRefExpr{
									pos:  position{line: 268, col: 70, offset: 6468},
									name: "Content",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnconstrainedType",
			pos:  position{line: 279, col: 1, offset: 6701},
			expr: &actionExpr{
				pos: position{line: 279, col: 22, offset: 6722},
				run: (*parser).callonUnconstrainedType1,
				expr: &litMatcher{
					pos:        position{line: 279, col: 22, offset: 6722},
					val:        "unconstrained",
					ignoreCase: false,
					want:       "\"unconstrained\"",
				},
			},
		},
		{
			name: "Content",
			pos:  position{line: 288, col: 1, offset: 6888},
			expr: &actionExpr{
				pos: position{line: 288, col: 12, offset: 6899},
				run: (*parser).callonContent1,
				expr: &oneOrMoreExpr{
					pos: position{line: 288, col: 12, offset: 6899},
					expr: &charClassMatcher{
						pos:        position{line: 288, col: 12, offset: 6899},
						val:        "[a-zA-Z0-9 -_.,#@!*=+]",
						chars:      []rune{'.', ',', '#', '@', '!', '*', '=', '+'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9', ' ', '_'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "ws",
			pos:  position{line: 292, col: 1, offset: 6957},
			expr: &oneOrMoreExpr{
				pos: position{line: 292, col: 7, offset: 6963},
				expr: &charClassMatcher{
					pos:        position{line: 292, col: 7, offset: 6963},
					val:        "[ ]",
					chars:      []rune{' '},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onRootDataType1(dataType any) (any, error) {
	return dataType.(*DataType), nil
}

func (p *parser) callonRootDataType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRootDataType1(stack["dataType"])
}

func (c *current) onRecordDataType1(fields any) (any, error) {
	fieldsSlice := fields.([]interface{})
	fieldList := make([]Field, len(fieldsSlice))
	for i, f := range fieldsSlice {
		fieldList[i] = f.(Field)
	}
	return &DataType{
		CollectionType: "record",
		RecordFields:   fieldList,
	}, nil
}

func (p *parser) callonRecordDataType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRecordDataType1(stack["fields"])
}

func (c *current) onFieldList1(first, rest any) (any, error) {
	result := []interface{}{first}
	for _, r := range rest.([]interface{}) {
		if slice, ok := r.([]interface{}); ok && len(slice) > 3 {
			result = append(result, slice[3]) // If the grammar changes, this index ends moving.
		}
	}
	return result, nil
}

func (p *parser) callonFieldList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldList1(stack["first"], stack["rest"])
}

func (c *current) onField1(name, dataType any) (any, error) {
	return Field{
		Name:          name.(string),
		FieldDataType: dataType.(*DataType),
	}, nil
}

func (p *parser) callonField1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["name"], stack["dataType"])
}

func (c *current) onFieldName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFieldName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldName1()
}

func (c *current) onCollectionDataType1(uniqueFlag, multiplicity, collectionType, atomic any) (any, error) {
	collectionTypeStr := collectionType.(string)
	atomicDt := atomic.(*DataType)

	// Set collection properties.
	// CollectionUnique is always set for collections (true or false).
	unique := parserBoolPtr(uniqueFlag != nil)

	// CollectionMin/Max are nil when not specified or when value is 0 (0 means "none").
	var min, max *int
	if multiplicity != nil {
		mult := multiplicity.(map[string]interface{})
		if m, ok := mult["min"]; ok {
			if minVal := m.(int); minVal > 0 {
				min = &minVal
			}
		}
		if m, ok := mult["max"]; ok {
			if maxVal := m.(int); maxVal > 0 {
				max = &maxVal
			}
		}
	}

	// Build name
	name := ""
	if *unique {
		name += "unique "
	}
	if min != nil || max != nil {
		if min != nil {
			name += strconv.Itoa(*min)
		} else {
			name += "0"
		}
		if max != nil {
			name += "-" + strconv.Itoa(*max)
		} else {
			name += "+"
		}
		name += " "
	}

	return &DataType{
		CollectionType:   collectionTypeStr,
		CollectionUnique: unique,
		CollectionMin:    min,
		CollectionMax:    max,
		Atomic:           atomicDt.Atomic,
	}, nil
}

func (p *parser) callonCollectionDataType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCollectionDataType1(stack["uniqueFlag"], stack["multiplicity"], stack["collectionType"], stack["atomic"])
}

func (c *current) onCollectionTypeKeyword1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCollectionTypeKeyword1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCollectionTypeKeyword1()
}

func (c *current) onMultiplicity1(min, suffix any) (any, error) {
	result := make(map[string]interface{})
	minVal := min.(int)
	result["min"] = minVal
	if suffix != nil {
		if suffixStr, ok := suffix.(string); ok && suffixStr == "+" {
			// It's "+", max is nil (unbounded)
		} else if suffixSlice, ok := suffix.([]interface{}); ok && len(suffixSlice) > 1 {
			// It's "-" maxVal
			maximum := suffixSlice[1].(int)
			result["max"] = maximum
		}
	}
	return result, nil
}

func (p *parser) callonMultiplicity1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicity1(stack["min"], stack["suffix"])
}

func (c *current) onAtomicDataType1(atomic any) (any, error) {
	return atomic, nil
}

func (p *parser) callonAtomicDataType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAtomicDataType1(stack["atomic"])
}

func (c *current) onSpanType1(lowerBracket, lowerValue, higherValue, higherBracket, precision, units any) (any, error) {

	// What are the bounds?
	lowerType := "open"
	higherType := "open"
	if lowerBracket.(string) == "[" {
		lowerType = "closed"
	}
	if higherBracket.(string) == "]" {
		higherType = "closed"
	}

	var lvPtr, ldPtr *int
	var hvPtr, hdPtr *int

	// lower value may be "unconstrained" or a map of values.
	if _, ok := lowerValue.(string); ok {
		lowerType = "unconstrained"
	} else {
		// Get the lower values.
		lm := lowerValue.(map[string]int)
		lv := lm["value"]
		ld := lm["denom"]
		lvPtr = &lv
		ldPtr = &ld
	}

	// higher value may be "unconstrained" or a map of values.
	if _, ok := higherValue.(string); ok {
		higherType = "unconstrained"
	} else {
		// Get the higher values.
		hm := higherValue.(map[string]int)
		hv := hm["value"]
		hd := hm["denom"]
		hvPtr = &hv
		hdPtr = &hd
	}

	return &DataType{
		CollectionType: COLLECTION_TYPE_ATOMIC,
		Atomic: &Atomic{
			ConstraintType: CONSTRAINT_TYPE_SPAN,
			Span: &AtomicSpan{
				LowerType:         lowerType,
				LowerValue:        lvPtr,
				LowerDenominator:  ldPtr,
				HigherType:        higherType,
				HigherValue:       hvPtr,
				HigherDenominator: hdPtr,
				Units:             units.(string),
				Precision:         precision.(float64),
			},
		},
	}, nil
}

func (p *parser) callonSpanType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpanType1(stack["lowerBracket"], stack["lowerValue"], stack["higherValue"], stack["higherBracket"], stack["precision"], stack["units"])
}

func (c *current) onFractionValue1(value, denom any) (any, error) {
	v := value.(int)
	d := 1
	if denomSlice, ok := denom.([]interface{}); ok && len(denomSlice) > 0 {
		d = denomSlice[3].(int)
		if d == 0 {
			return nil, errors.New("denominator cannot be zero")
		}
	}
	return map[string]int{"value": v, "denom": d}, nil
}

func (p *parser) callonFractionValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFractionValue1(stack["value"], stack["denom"])
}

func (c *current) onInteger1() (any, error) {
	return strconv.Atoi(string(c.text))
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onFloat1() (any, error) {
	str := string(c.text)
	val, _ := strconv.ParseFloat(str, 64)
	return val, nil
}

func (p *parser) callonFloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onLowerBracket1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLowerBracket1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLowerBracket1()
}

func (c *current) onHigherBracket1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonHigherBracket1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHigherBracket1()
}

func (c *current) onUnconstrained1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnconstrained1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnconstrained1()
}

func (c *current) onUnits1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnits1()
}

func (c *current) onOrdEnumType1(enumeration any) (any, error) {
	// Make it ordered.
	enumType := enumeration.(*DataType)
	enumType.Atomic.EnumOrdered = parserBoolPtr(true)
	return enumType, nil
}

func (p *parser) callonOrdEnumType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrdEnumType1(stack["enumeration"])
}

func (c *current) onEnumType1(enumValues any) (any, error) {
	valuesBytes := enumValues.([]interface{})
	valuesStr := ""
	for _, b := range valuesBytes {
		valuesStr += string(b.([]byte))
	}
	valuesStr = strings.TrimSpace(valuesStr)
	// Split by comma and trim spaces
	parts := strings.Split(valuesStr, ",")
	var enums []AtomicEnum
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed != "" {
			enums = append(enums, AtomicEnum{Value: trimmed})
		}
	}
	return &DataType{
		CollectionType: COLLECTION_TYPE_ATOMIC,
		Atomic: &Atomic{
			ConstraintType: CONSTRAINT_TYPE_ENUMERATION,
			EnumOrdered:    parserBoolPtr(false),
			Enums:          enums,
		},
	}, nil
}

func (p *parser) callonEnumType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnumType1(stack["enumValues"])
}

func (c *current) onObjectType1(content any) (any, error) {
	contentStr := strings.TrimSpace(content.(string))
	return &DataType{
		CollectionType: COLLECTION_TYPE_ATOMIC,
		Atomic: &Atomic{
			ConstraintType: CONSTRAINT_TYPE_OBJECT,
			ObjectClassKey: &contentStr,
		},
	}, nil
}

func (p *parser) callonObjectType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectType1(stack["content"])
}

func (c *current) onReferenceType1(content any) (any, error) {
	contentStr := strings.TrimSpace(content.(string))
	return &DataType{
		CollectionType: COLLECTION_TYPE_ATOMIC,
		Atomic: &Atomic{
			ConstraintType: CONSTRAINT_TYPE_REFERENCE,
			Reference:      &contentStr,
		},
	}, nil
}

func (p *parser) callonReferenceType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceType1(stack["content"])
}

func (c *current) onUnconstrainedType1() (any, error) {
	return &DataType{
		CollectionType: COLLECTION_TYPE_ATOMIC,
		Atomic: &Atomic{
			ConstraintType: CONSTRAINT_TYPE_UNCONSTRAINED,
		},
	}, nil
}

func (p *parser) callonUnconstrainedType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnconstrainedType1()
}

func (c *current) onContent1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onContent1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
