version: "2"
linters:
  enable:
    - dupword
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - godot
    - gosec
    - intrange
    - misspell
    - modernize
    - nilnil
    - noctx
    - recvcheck
    - revive
    - rowserrcheck
    - testifylint
    - unconvert
    - unparam
    - whitespace

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
          - forbidigo
          - gocritic
          - revive
        path: .*_test\.go$
      - linters:
          - staticcheck
        text: "QF1012"
      - linters:
          - revive
        text: "var-naming: don't use an underscore in package name"
      - linters:
          - revive
        text: "var-naming: don't use ALL_CAPS in Go names"
    paths:
      - .*\.generated\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
