// Code generated by pigeon; DO NOT EDIT.

package data_type

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "DataType",
			pos:  position{line: 10, col: 1, offset: 57},
			expr: &choiceExpr{
				pos: position{line: 10, col: 13, offset: 69},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 10, col: 13, offset: 69},
						name: "SpanType",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 24, offset: 80},
						name: "OrdEnumType",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 38, offset: 94},
						name: "EnumType",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 49, offset: 105},
						name: "ObjectType",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 62, offset: 118},
						name: "ReferenceType",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 78, offset: 134},
						name: "UnconstrainedType",
					},
				},
			},
		},
		{
			name: "SpanType",
			pos:  position{line: 12, col: 1, offset: 153},
			expr: &actionExpr{
				pos: position{line: 12, col: 13, offset: 165},
				run: (*parser).callonSpanType1,
				expr: &seqExpr{
					pos: position{line: 12, col: 13, offset: 165},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 12, col: 13, offset: 165},
							label: "lowerBracket",
							expr: &ruleRefExpr{
								pos:  position{line: 12, col: 26, offset: 178},
								name: "LowerBracket",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 39, offset: 191},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 12, col: 42, offset: 194},
							label: "lowerValue",
							expr: &choiceExpr{
								pos: position{line: 12, col: 55, offset: 207},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 12, col: 55, offset: 207},
										name: "Unconstrained",
									},
									&ruleRefExpr{
										pos:  position{line: 12, col: 71, offset: 223},
										name: "FractionValue",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 87, offset: 239},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 12, col: 90, offset: 242},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&litMatcher{
							pos:        position{line: 12, col: 94, offset: 246},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 98, offset: 250},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 12, col: 101, offset: 253},
							label: "higherValue",
							expr: &choiceExpr{
								pos: position{line: 12, col: 115, offset: 267},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 12, col: 115, offset: 267},
										name: "Unconstrained",
									},
									&ruleRefExpr{
										pos:  position{line: 12, col: 131, offset: 283},
										name: "FractionValue",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 147, offset: 299},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 12, col: 150, offset: 302},
							label: "higherBracket",
							expr: &ruleRefExpr{
								pos:  position{line: 12, col: 164, offset: 316},
								name: "HigherBracket",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 178, offset: 330},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 12, col: 181, offset: 333},
							label: "units",
							expr: &ruleRefExpr{
								pos:  position{line: 12, col: 187, offset: 339},
								name: "Units",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 12, col: 193, offset: 345},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 12, col: 196, offset: 348},
							label: "precision",
							expr: &ruleRefExpr{
								pos:  position{line: 12, col: 206, offset: 358},
								name: "Float",
							},
						},
					},
				},
			},
		},
		{
			name: "FractionValue",
			pos:  position{line: 69, col: 1, offset: 1575},
			expr: &actionExpr{
				pos: position{line: 69, col: 18, offset: 1592},
				run: (*parser).callonFractionValue1,
				expr: &seqExpr{
					pos: position{line: 69, col: 20, offset: 1594},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 69, col: 20, offset: 1594},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 69, col: 26, offset: 1600},
								name: "Integer",
							},
						},
						&labeledExpr{
							pos:   position{line: 69, col: 34, offset: 1608},
							label: "denom",
							expr: &zeroOrOneExpr{
								pos: position{line: 69, col: 40, offset: 1614},
								expr: &seqExpr{
									pos: position{line: 69, col: 42, offset: 1616},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 69, col: 42, offset: 1616},
											name: "ws",
										},
										&litMatcher{
											pos:        position{line: 69, col: 45, offset: 1619},
											val:        "/",
											ignoreCase: false,
											want:       "\"/\"",
										},
										&ruleRefExpr{
											pos:  position{line: 69, col: 49, offset: 1623},
											name: "ws",
										},
										&labeledExpr{
											pos:   position{line: 69, col: 52, offset: 1626},
											label: "denomValue",
											expr: &ruleRefExpr{
												pos:  position{line: 69, col: 63, offset: 1637},
												name: "Integer",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 81, col: 1, offset: 1909},
			expr: &actionExpr{
				pos: position{line: 81, col: 12, offset: 1920},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 81, col: 12, offset: 1920},
					expr: &charClassMatcher{
						pos:        position{line: 81, col: 12, offset: 1920},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 85, col: 1, offset: 1969},
			expr: &actionExpr{
				pos: position{line: 85, col: 10, offset: 1978},
				run: (*parser).callonFloat1,
				expr: &choiceExpr{
					pos: position{line: 85, col: 12, offset: 1980},
					alternatives: []any{
						&seqExpr{
							pos: position{line: 85, col: 12, offset: 1980},
							exprs: []any{
								&oneOrMoreExpr{
									pos: position{line: 85, col: 12, offset: 1980},
									expr: &charClassMatcher{
										pos:        position{line: 85, col: 12, offset: 1980},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 85, col: 19, offset: 1987},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 85, col: 23, offset: 1991},
									expr: &charClassMatcher{
										pos:        position{line: 85, col: 23, offset: 1991},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
						&seqExpr{
							pos: position{line: 85, col: 32, offset: 2000},
							exprs: []any{
								&zeroOrMoreExpr{
									pos: position{line: 85, col: 32, offset: 2000},
									expr: &charClassMatcher{
										pos:        position{line: 85, col: 32, offset: 2000},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 85, col: 39, offset: 2007},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 85, col: 43, offset: 2011},
									expr: &charClassMatcher{
										pos:        position{line: 85, col: 43, offset: 2011},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 85, col: 52, offset: 2020},
							expr: &charClassMatcher{
								pos:        position{line: 85, col: 52, offset: 2020},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Unconstrained",
			pos:  position{line: 91, col: 1, offset: 2113},
			expr: &actionExpr{
				pos: position{line: 91, col: 18, offset: 2130},
				run: (*parser).callonUnconstrained1,
				expr: &litMatcher{
					pos:        position{line: 91, col: 20, offset: 2132},
					val:        "unconstrained",
					ignoreCase: false,
					want:       "\"unconstrained\"",
				},
			},
		},
		{
			name: "LowerBracket",
			pos:  position{line: 96, col: 1, offset: 2184},
			expr: &actionExpr{
				pos: position{line: 96, col: 17, offset: 2200},
				run: (*parser).callonLowerBracket1,
				expr: &choiceExpr{
					pos: position{line: 96, col: 19, offset: 2202},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 96, col: 19, offset: 2202},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&litMatcher{
							pos:        position{line: 96, col: 25, offset: 2208},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
					},
				},
			},
		},
		{
			name: "HigherBracket",
			pos:  position{line: 100, col: 1, offset: 2247},
			expr: &actionExpr{
				pos: position{line: 100, col: 18, offset: 2264},
				run: (*parser).callonHigherBracket1,
				expr: &choiceExpr{
					pos: position{line: 100, col: 20, offset: 2266},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 100, col: 20, offset: 2266},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&litMatcher{
							pos:        position{line: 100, col: 26, offset: 2272},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Units",
			pos:  position{line: 104, col: 1, offset: 2311},
			expr: &actionExpr{
				pos: position{line: 104, col: 10, offset: 2320},
				run: (*parser).callonUnits1,
				expr: &oneOrMoreExpr{
					pos: position{line: 104, col: 10, offset: 2320},
					expr: &charClassMatcher{
						pos:        position{line: 104, col: 10, offset: 2320},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "UnconstrainedType",
			pos:  position{line: 108, col: 1, offset: 2363},
			expr: &actionExpr{
				pos: position{line: 108, col: 22, offset: 2384},
				run: (*parser).callonUnconstrainedType1,
				expr: &seqExpr{
					pos: position{line: 108, col: 22, offset: 2384},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 108, col: 22, offset: 2384},
							name: "ws",
						},
						&notExpr{
							pos: position{line: 108, col: 25, offset: 2387},
							expr: &anyMatcher{
								line: 108, col: 26, offset: 2388,
							},
						},
					},
				},
			},
		},
		{
			name: "OrdEnumType",
			pos:  position{line: 118, col: 1, offset: 2545},
			expr: &actionExpr{
				pos: position{line: 118, col: 16, offset: 2560},
				run: (*parser).callonOrdEnumType1,
				expr: &seqExpr{
					pos: position{line: 118, col: 16, offset: 2560},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 118, col: 16, offset: 2560},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 118, col: 20, offset: 2564},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 118, col: 20, offset: 2564},
									val:        "ordered-enumeration",
									ignoreCase: false,
									want:       "\"ordered-enumeration\"",
								},
								&litMatcher{
									pos:        position{line: 118, col: 44, offset: 2588},
									val:        "ord-enum",
									ignoreCase: false,
									want:       "\"ord-enum\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 56, offset: 2600},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 118, col: 59, offset: 2603},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 63, offset: 2607},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 66, offset: 2610},
							label: "enumValues",
							expr: &zeroOrMoreExpr{
								pos: position{line: 118, col: 77, offset: 2621},
								expr: &anyMatcher{
									line: 118, col: 77, offset: 2621,
								},
							},
						},
						&notExpr{
							pos: position{line: 118, col: 80, offset: 2624},
							expr: &anyMatcher{
								line: 118, col: 81, offset: 2625,
							},
						},
					},
				},
			},
		},
		{
			name: "EnumType",
			pos:  position{line: 147, col: 1, offset: 3294},
			expr: &actionExpr{
				pos: position{line: 147, col: 13, offset: 3306},
				run: (*parser).callonEnumType1,
				expr: &seqExpr{
					pos: position{line: 147, col: 13, offset: 3306},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 147, col: 13, offset: 3306},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 147, col: 17, offset: 3310},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 147, col: 17, offset: 3310},
									val:        "enumeration",
									ignoreCase: false,
									want:       "\"enumeration\"",
								},
								&litMatcher{
									pos:        position{line: 147, col: 33, offset: 3326},
									val:        "enum",
									ignoreCase: false,
									want:       "\"enum\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 147, col: 41, offset: 3334},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 147, col: 44, offset: 3337},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 147, col: 48, offset: 3341},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 147, col: 51, offset: 3344},
							label: "enumValues",
							expr: &zeroOrMoreExpr{
								pos: position{line: 147, col: 62, offset: 3355},
								expr: &anyMatcher{
									line: 147, col: 62, offset: 3355,
								},
							},
						},
						&notExpr{
							pos: position{line: 147, col: 65, offset: 3358},
							expr: &anyMatcher{
								line: 147, col: 66, offset: 3359,
							},
						},
					},
				},
			},
		},
		{
			name: "ObjectType",
			pos:  position{line: 176, col: 1, offset: 4027},
			expr: &actionExpr{
				pos: position{line: 176, col: 15, offset: 4041},
				run: (*parser).callonObjectType1,
				expr: &seqExpr{
					pos: position{line: 176, col: 15, offset: 4041},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 176, col: 15, offset: 4041},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 176, col: 19, offset: 4045},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 176, col: 19, offset: 4045},
									val:        "object",
									ignoreCase: false,
									want:       "\"object\"",
								},
								&litMatcher{
									pos:        position{line: 176, col: 30, offset: 4056},
									val:        "obj",
									ignoreCase: false,
									want:       "\"obj\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 176, col: 37, offset: 4063},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 176, col: 40, offset: 4066},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 176, col: 44, offset: 4070},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 176, col: 47, offset: 4073},
							label: "classKey",
							expr: &zeroOrMoreExpr{
								pos: position{line: 176, col: 56, offset: 4082},
								expr: &anyMatcher{
									line: 176, col: 56, offset: 4082,
								},
							},
						},
						&notExpr{
							pos: position{line: 176, col: 59, offset: 4085},
							expr: &anyMatcher{
								line: 176, col: 60, offset: 4086,
							},
						},
					},
				},
			},
		},
		{
			name: "ReferenceType",
			pos:  position{line: 194, col: 1, offset: 4446},
			expr: &actionExpr{
				pos: position{line: 194, col: 18, offset: 4463},
				run: (*parser).callonReferenceType1,
				expr: &seqExpr{
					pos: position{line: 194, col: 18, offset: 4463},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 194, col: 18, offset: 4463},
							name: "ws",
						},
						&choiceExpr{
							pos: position{line: 194, col: 22, offset: 4467},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 194, col: 22, offset: 4467},
									val:        "reference",
									ignoreCase: false,
									want:       "\"reference\"",
								},
								&litMatcher{
									pos:        position{line: 194, col: 36, offset: 4481},
									val:        "ref",
									ignoreCase: false,
									want:       "\"ref\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 194, col: 43, offset: 4488},
							name: "ws",
						},
						&litMatcher{
							pos:        position{line: 194, col: 46, offset: 4491},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 194, col: 50, offset: 4495},
							name: "ws",
						},
						&labeledExpr{
							pos:   position{line: 194, col: 53, offset: 4498},
							label: "ref",
							expr: &zeroOrMoreExpr{
								pos: position{line: 194, col: 57, offset: 4502},
								expr: &anyMatcher{
									line: 194, col: 57, offset: 4502,
								},
							},
						},
						&notExpr{
							pos: position{line: 194, col: 60, offset: 4505},
							expr: &anyMatcher{
								line: 194, col: 61, offset: 4506,
							},
						},
					},
				},
			},
		},
		{
			name: "ws",
			pos:  position{line: 212, col: 1, offset: 4843},
			expr: &zeroOrMoreExpr{
				pos: position{line: 212, col: 7, offset: 4849},
				expr: &charClassMatcher{
					pos:        position{line: 212, col: 7, offset: 4849},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onSpanType1(lowerBracket, lowerValue, higherValue, higherBracket, units, precision any) (any, error) {

	// What are the bounds?
	lowerType := "open"
	higherType := "open"
	if lowerBracket.(string) == "[" {
		lowerType = "closed"
	}
	if higherBracket.(string) == "]" {
		higherType = "closed"
	}

	var lvPtr, ldPtr *int
	var hvPtr, hdPtr *int

	// lower value may be "unconstrained" or a map of values.
	if _, ok := lowerValue.(string); ok {
		lowerType = "unconstrained"
	} else {
		// Get the lower values.
		lm := lowerValue.(map[string]int)
		lv := lm["value"]
		ld := lm["denom"]
		lvPtr = &lv
		ldPtr = &ld
	}

	// higher value may be "unconstrained" or a map of values.
	if _, ok := higherValue.(string); ok {
		higherType = "unconstrained"
	} else {
		// Get the higher values.
		hm := higherValue.(map[string]int)
		hv := hm["value"]
		hd := hm["denom"]
		hvPtr = &hv
		hdPtr = &hd
	}

	return &DataType{
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "span",
			Span: &AtomicSpan{
				LowerType:         lowerType,
				LowerValue:        lvPtr,
				LowerDenominator:  ldPtr,
				HigherType:        higherType,
				HigherValue:       hvPtr,
				HigherDenominator: hdPtr,
				Units:             units.(string),
				Precision:         precision.(float64),
			},
		},
	}, nil
}

func (p *parser) callonSpanType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpanType1(stack["lowerBracket"], stack["lowerValue"], stack["higherValue"], stack["higherBracket"], stack["units"], stack["precision"])
}

func (c *current) onFractionValue1(value, denom any) (any, error) {
	v := value.(int)
	d := 1
	if denomSlice, ok := denom.([]interface{}); ok && len(denomSlice) > 0 {
		d = denomSlice[3].(int)
		if d == 0 {
			return nil, errors.New("denominator cannot be zero")
		}
	}
	return map[string]int{"value": v, "denom": d}, nil
}

func (p *parser) callonFractionValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFractionValue1(stack["value"], stack["denom"])
}

func (c *current) onInteger1() (any, error) {
	return strconv.Atoi(string(c.text))
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onFloat1() (any, error) {
	str := string(c.text)
	val, _ := strconv.ParseFloat(str, 64)
	return val, nil
}

func (p *parser) callonFloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onUnconstrained1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnconstrained1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnconstrained1()
}

func (c *current) onLowerBracket1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLowerBracket1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLowerBracket1()
}

func (c *current) onHigherBracket1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonHigherBracket1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHigherBracket1()
}

func (c *current) onUnits1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnits1()
}

func (c *current) onUnconstrainedType1() (any, error) {
	return &DataType{
		Name:           "unconstrained",
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "unconstrained",
		},
	}, nil
}

func (p *parser) callonUnconstrainedType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnconstrainedType1()
}

func (c *current) onOrdEnumType1(enumValues any) (any, error) {
	valuesBytes := enumValues.([]interface{})
	valuesStr := ""
	for _, b := range valuesBytes {
		valuesStr += string(b.([]byte))
	}
	valuesStr = strings.TrimSpace(valuesStr)
	// Split by comma and trim spaces
	parts := strings.Split(valuesStr, ",")
	var enums []AtomicEnum
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed != "" {
			enums = append(enums, AtomicEnum{Value: trimmed})
		}
	}
	name := "ord-enum: " + valuesStr
	trueVal := true
	return &DataType{
		Name:           name,
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "enumeration",
			EnumOrdered:    &trueVal,
			Enums:          enums,
		},
	}, nil
}

func (p *parser) callonOrdEnumType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrdEnumType1(stack["enumValues"])
}

func (c *current) onEnumType1(enumValues any) (any, error) {
	valuesBytes := enumValues.([]interface{})
	valuesStr := ""
	for _, b := range valuesBytes {
		valuesStr += string(b.([]byte))
	}
	valuesStr = strings.TrimSpace(valuesStr)
	// Split by comma and trim spaces
	parts := strings.Split(valuesStr, ",")
	var enums []AtomicEnum
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed != "" {
			enums = append(enums, AtomicEnum{Value: trimmed})
		}
	}
	name := "enum: " + valuesStr
	falseVal := false
	return &DataType{
		Name:           name,
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "enumeration",
			EnumOrdered:    &falseVal,
			Enums:          enums,
		},
	}, nil
}

func (p *parser) callonEnumType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnumType1(stack["enumValues"])
}

func (c *current) onObjectType1(classKey any) (any, error) {
	classBytes := classKey.([]interface{})
	classStr := ""
	for _, b := range classBytes {
		classStr += string(b.([]byte))
	}
	classStr = strings.TrimSpace(classStr)
	name := "obj: " + classStr
	return &DataType{
		Name:           name,
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "object",
			ObjectClassKey: classStr,
		},
	}, nil
}

func (p *parser) callonObjectType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectType1(stack["classKey"])
}

func (c *current) onReferenceType1(ref any) (any, error) {
	refBytes := ref.([]interface{})
	refStr := ""
	for _, b := range refBytes {
		refStr += string(b.([]byte))
	}
	refStr = strings.TrimSpace(refStr)
	name := "ref: " + refStr
	return &DataType{
		Name:           name,
		CollectionType: "atomic",
		Atomic: &Atomic{
			ConstraintType: "reference",
			Reference:      refStr,
		},
	}, nil
}

func (p *parser) callonReferenceType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReferenceType1(stack["ref"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
